services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next
    networks:
      - public
    ports:
      - "8081:8081"

networks:
  public:
    name: public-network
    external: true
